# Generated by Django 3.0.7 on 2021-01-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210124_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(default='movie', max_length=6),
            preserve_default=False,
        ),
    ]
