# Generated by Django 3.0.7 on 2021-01-25 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_video_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
    ]
