# Generated by Django 3.0.7 on 2021-01-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_link_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='quality',
            field=models.CharField(default='720p', max_length=5),
            preserve_default=False,
        ),
    ]
