# Generated by Django 3.0.7 on 2021-01-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_video_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='seasons',
            field=models.IntegerField(null=True),
        ),
    ]
