# Generated by Django 3.0.7 on 2021-01-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210126_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
